[package]
name = "book"
version = "0.1.0"
authors = ["Nick Lehmann <nick@lehmann.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mybin"
path = "src/lib.rs"

[dependencies]
